import "~/styles/globals.css";
import { Inter as FontSans } from "next/font/google"

import { ClerkProvider } from "@clerk/nextjs";

import { cn } from "~/lib/utils"
import { Toaster } from "~/components/ui/toaster"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "T3 Gallery",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
          )}
        >
          {children}
        </body>
        <Toaster />
      </html>
    </ClerkProvider>
  );
}
